In [ ]:
!pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.29.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2026.4.22)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)

In [2]:
import pandas as pd

sheet_id = '1RB9p1NHmQzp37iyDdRVBQDa3uDyhHAHqHySXiAfRWkM'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv'

df = pd.read_csv(url)
df.head()

,user_id,date,day_of_week,age,gender,weight_kg,height_cm,fitness_level,primary_sport,recovery_score,...,activity_strain,avg_heart_rate,max_heart_rate,activity_calories,hr_zone_1_min,hr_zone_2_min,hr_zone_3_min,hr_zone_4_min,hr_zone_5_min,workout_time_of_day
0,USER_00001,2023-01-01,Sunday,56,Female,53.9,167.2,Beginner,Weight Training,57.8,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,USER_00001,2023-01-02,Monday,56,Female,53.9,167.2,Beginner,Weight Training,62.6,...,7.47,121.2,137.6,371.0,11.9,18.0,15.9,11.6,4.6,Evening
2,USER_00001,2023-01-03,Tuesday,56,Female,53.9,167.2,Beginner,Weight Training,81.5,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,USER_00001,2023-01-04,Wednesday,56,Female,53.9,167.2,Beginner,Weight Training,55.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,USER_00001,2023-01-05,Thursday,56,Female,53.9,167.2,Beginner,Weight Training,62.5,...,15.27,136.4,152.8,623.0,3.7,6.0,13.7,18.6,9.0,Evening

In [3]:
!pip install pandas numpy requests scikit-learn sqlalchemy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.50)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.5.20)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
def extract_etl_source1():

    start_time = time.time()

    sheet_id = "1RB9p1NHmQzp37iyDdRVBQDa3uDyhHAHqHySXiAfRWkM"

    url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"

    df = pd.read_csv(url)

    # simpan raw copy
    df.to_csv(
        f"{RAW_PATH}/whoop_fitness_raw.csv",
        index=False
    )

    execution_time = time.time() - start_time

    log_message = f"""
    ===== EXTRACT SOURCE 1 =====
    Source: Google Sheets
    Rows: {df.shape[0]}
    Columns: {df.shape[1]}
    Execution Time: {execution_time:.2f}
    Timestamp: {datetime.now()}
    """

    write_log(log_message, "extract_log.txt")

    print("SOURCE 1 EXTRACTED")

    return df

In [5]:
print(df.shape)

print(df.info())

print(df.isnull().sum())

(100000, 39)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 39 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   user_id                  100000 non-null  object
 1   date                     100000 non-null  object
 2   day_of_week              100000 non-null  object
 3   age                      100000 non-null  int64
 4   gender                   100000 non-null  object
 5   weight_kg                100000 non-null  float64
 6   height_cm                100000 non-null  float64
 7   fitness_level            100000 non-null  object
 8   primary_sport            100000 non-null  object
 9   recovery_score           100000 non-null  float64
 10  day_strain               100000 non-null  float64
 11  sleep_hours              100000 non-null  float64
 12  sleep_efficiency         100000 non-null  float64
 13  sleep_performance        100000 non-null  float64
 14  light_sleep_hours        100000 non-null  float64
 15  rem_sleep_hours          100000 non-null  float64
 16  deep_sleep_hours         100000 non-null  float64
 17  wake_ups                 100000 non-null  int64
 18  time_to_fall_asleep_min  100000 non-null  float64
 19  hrv                      100000 non-null  float64
 20  resting_heart_rate       100000 non-null  float64
 21  hrv_baseline             100000 non-null  int64
 22  rhr_baseline             100000 non-null  int64
 23  respiratory_rate         100000 non-null  float64
 24  skin_temp_deviation      100000 non-null  float64
 25  calories_burned          100000 non-null  float64
 26  workout_completed        100000 non-null  int64
 27  activity_type            100000 non-null  object
 28  activity_duration_min    100000 non-null  int64
 29  activity_strain          100000 non-null  float64
 30  avg_heart_rate           100000 non-null  float64
 31  max_heart_rate           100000 non-null  float64
 32  activity_calories        100000 non-null  float64
 33  hr_zone_1_min            100000 non-null  float64
 34  hr_zone_2_min            100000 non-null  float64
 35  hr_zone_3_min            100000 non-null  float64
 36  hr_zone_4_min            100000 non-null  float64
 37  hr_zone_5_min            100000 non-null  float64
 38  workout_time_of_day      54010 non-null   object
dtypes: float64(25), int64(6), object(8)
memory usage: 29.8+ MB
None
user_id                        0
date                           0
day_of_week                    0
age                            0
gender                         0
weight_kg                      0
height_cm                      0
fitness_level                  0
primary_sport                  0
recovery_score                 0
day_strain                     0
sleep_hours                    0
sleep_efficiency               0
sleep_performance              0
light_sleep_hours              0
rem_sleep_hours                0
deep_sleep_hours               0
wake_ups                       0
time_to_fall_asleep_min        0
hrv                            0
resting_heart_rate             0
hrv_baseline                   0
rhr_baseline                   0
respiratory_rate               0
skin_temp_deviation            0
calories_burned                0
workout_completed              0
activity_type                  0
activity_duration_min          0
activity_strain                0
avg_heart_rate                 0
max_heart_rate                 0
activity_calories              0
hr_zone_1_min                  0
hr_zone_2_min                  0
hr_zone_3_min                  0
hr_zone_4_min                  0
hr_zone_5_min                  0
workout_time_of_day        45990
dtype: int64

#####6.1 Extract

In [6]:
import pandas as pd
import numpy as np
import requests
import json
import os
import shutil
import sqlite3
import time

from datetime import datetime

In [7]:
BASE_PATH = "/content/drive/MyDrive/bigdata_final_project"

DATASET_PATH = f"{BASE_PATH}/dataset"
RAW_PATH = f"{BASE_PATH}/raw"
LOG_PATH = f"{BASE_PATH}/logs"
WAREHOUSE_PATH = f"{BASE_PATH}/warehouse"

os.makedirs(RAW_PATH, exist_ok=True)
os.makedirs(LOG_PATH, exist_ok=True)
os.makedirs(WAREHOUSE_PATH, exist_ok=True)

In [8]:
def write_log(message, filename):

    with open(f"{LOG_PATH}/{filename}", "a") as f:
        f.write(message + "\n")

In [9]:
def extract_etl_source1():

    start_time = time.time()

    source_file = f"{DATASET_PATH}/whoop_fitness_dataset_100k.csv"

    raw_destination = f"{RAW_PATH}/whoop_fitness_raw.csv"

    # copy raw data
    shutil.copy(source_file, raw_destination)

    # load data
    df = pd.read_csv(source_file)

    execution_time = time.time() - start_time

    file_size = os.path.getsize(source_file) / (1024 * 1024)

    log_message = f"""
    ===== EXTRACT SOURCE 1 =====
    Source: WHOOP Dataset CSV
    Rows: {df.shape[0]}
    Columns: {df.shape[1]}
    File Size: {file_size:.2f} MB
    Execution Time: {execution_time:.2f} seconds
    Timestamp: {datetime.now()}
    """

    write_log(log_message, "extract_log.txt")

    print("SOURCE 1 SUCCESSFULLY EXTRACTED")

    return df

In [10]:
def extract_etl_source2():

    start_time = time.time()

    api_key = "daf58d6f371c61a8b954569aea034b6e"

    city = "Jakarta"

    url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric"

    response = requests.get(url)

    weather_data = response.json()

    # save raw json
    with open(f"{RAW_PATH}/weather_raw.json", "w") as f:
        json.dump(weather_data, f, indent=4)

    execution_time = time.time() - start_time

    log_message = f"""
    ===== EXTRACT SOURCE 2 =====
    Source: OpenWeather API
    Format: JSON
    Execution Time: {execution_time:.2f} seconds
    Timestamp: {datetime.now()}
    """

    write_log(log_message, "extract_log.txt")

    print("SOURCE 2 SUCCESSFULLY EXTRACTED")

    return weather_data

In [11]:
import requests

api_key = "daf58d6f371c61a8b954569aea034b6e"

url = f"https://api.openweathermap.org/data/2.5/weather?q=Jakarta&appid={api_key}&units=metric"

response = requests.get(url)

weather_json = response.json()

print(weather_json)

{'coord': {'lon': 106.8451, 'lat': -6.2146}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'base': 'stations', 'main': {'temp': 28.49, 'feels_like': 32.3, 'temp_min': 26.61, 'temp_max': 30.05, 'pressure': 1012, 'humidity': 74, 'sea_level': 1012, 'grnd_level': 1007}, 'visibility': 10000, 'wind': {'speed': 1.34, 'deg': 108, 'gust': 1.34}, 'clouds': {'all': 100}, 'dt': 1781385775, 'sys': {'type': 2, 'id': 2108225, 'country': 'ID', 'sunrise': 1781391597, 'sunset': 1781433947}, 'timezone': 25200, 'id': 1642911, 'name': 'Jakarta', 'cod': 200}

####6.2 Tranform

In [14]:
transform_df = df.copy()

print("Shape Awal:", transform_df.shape)

Shape Awal: (100000, 39)

In [15]:
duplicate_count = transform_df.duplicated(
    subset=['user_id','date']
).sum()

print("Jumlah Duplicate:", duplicate_count)

Jumlah Duplicate: 0

In [16]:
transform_df = transform_df.drop_duplicates(
    subset=['user_id','date']
)

print("Shape Setelah Duplicate Removal:",
      transform_df.shape)

Shape Setelah Duplicate Removal: (100000, 39)

Missing value handling

In [17]:
transform_df.isnull().sum()

user_id                        0
date                           0
day_of_week                    0
age                            0
gender                         0
weight_kg                      0
height_cm                      0
fitness_level                  0
primary_sport                  0
recovery_score                 0
day_strain                     0
sleep_hours                    0
sleep_efficiency               0
sleep_performance              0
light_sleep_hours              0
rem_sleep_hours                0
deep_sleep_hours               0
wake_ups                       0
time_to_fall_asleep_min        0
hrv                            0
resting_heart_rate             0
hrv_baseline                   0
rhr_baseline                   0
respiratory_rate               0
skin_temp_deviation            0
calories_burned                0
workout_completed              0
activity_type                  0
activity_duration_min          0
activity_strain                0
avg_heart_rate                 0
max_heart_rate                 0
activity_calories              0
hr_zone_1_min                  0
hr_zone_2_min                  0
hr_zone_3_min                  0
hr_zone_4_min                  0
hr_zone_5_min                  0
workout_time_of_day        45990
dtype: int64

In [18]:
transform_df['workout_time_of_day'] = (
    transform_df['workout_time_of_day']
    .fillna('No Workout')
)

In [19]:
transform_df['workout_time_of_day'].isnull().sum()

np.int64(0)

Standarisasi data

In [20]:
transform_df.columns = (
    transform_df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

In [21]:
transform_df.columns.tolist()

['user_id',
 'date',
 'day_of_week',
 'age',
 'gender',
 'weight_kg',
 'height_cm',
 'fitness_level',
 'primary_sport',
 'recovery_score',
 'day_strain',
 'sleep_hours',
 'sleep_efficiency',
 'sleep_performance',
 'light_sleep_hours',
 'rem_sleep_hours',
 'deep_sleep_hours',
 'wake_ups',
 'time_to_fall_asleep_min',
 'hrv',
 'resting_heart_rate',
 'hrv_baseline',
 'rhr_baseline',
 'respiratory_rate',
 'skin_temp_deviation',
 'calories_burned',
 'workout_completed',
 'activity_type',
 'activity_duration_min',
 'activity_strain',
 'avg_heart_rate',
 'max_heart_rate',
 'activity_calories',
 'hr_zone_1_min',
 'hr_zone_2_min',
 'hr_zone_3_min',
 'hr_zone_4_min',
 'hr_zone_5_min',
 'workout_time_of_day']

Konversi datetime

In [22]:
transform_df['date'] = pd.to_datetime(
    transform_df['date']
)

In [23]:
transform_df['date'].dtype

dtype('<M8[ns]')

In [24]:
transform_df['gender'] = (
    transform_df['gender']
    .astype('category')
)

transform_df['fitness_level'] = (
    transform_df['fitness_level']
    .astype('category')
)

transform_df['activity_type'] = (
    transform_df['activity_type']
    .astype('category')
)

Normalisasi data

In [25]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

transform_df[
    [
        'recovery_score_norm',
        'sleep_hours_norm'
    ]
] = scaler.fit_transform(
    transform_df[
        [
            'recovery_score',
            'sleep_hours'
        ]
    ]
)

In [26]:
transform_df[
    [
        'recovery_score',
        'recovery_score_norm'
    ]
].head()

   recovery_score  recovery_score_norm
0            57.8             0.555789
1            62.6             0.606316
2            81.5             0.805263
3            55.0             0.526316
4            62.5             0.605263

Encoding data

In [27]:
transform_df['gender_encoded'] = (
    transform_df['gender']
    .cat.codes
)

In [52]:
transform_df[
    [
        'gender',
        'gender_encoded'
    ]
].head()

   gender  gender_encoded
0  Female               0
1  Female               0
2  Female               0
3  Female               0
4  Female               0

Data Enrichment

In [53]:
temperature = weather_json['main']['temp']
humidity = weather_json['main']['humidity']

transform_df['temperature'] = temperature
transform_df['humidity'] = humidity

In [54]:
transform_df['temperature'] = temperature

transform_df['humidity'] = humidity

####Feature engineering

BMI

In [55]:
transform_df['bmi'] = (
    transform_df['weight_kg'] /
    ((transform_df['height_cm']/100)**2)
)

Recovery level

In [56]:
transform_df['recovery_level'] = pd.cut(
    transform_df['recovery_score'],
    bins=[0,33,66,100],
    labels=[
        'Low',
        'Medium',
        'High'
    ]
)

Sleep Quality

In [57]:
transform_df['sleep_quality'] = pd.cut(
    transform_df['sleep_efficiency'],
    bins=[0,70,85,100],
    labels=[
        'Poor',
        'Good',
        'Excellent'
    ]
)

Strain level

In [58]:
transform_df['strain_level'] = pd.cut(
    transform_df['day_strain'],
    bins=[0,7,14,21],
    labels=[
        'Low',
        'Moderate',
        'High'
    ]
)

Fatigue Index

In [59]:
transform_df['fatigue_index'] = (
    transform_df['day_strain'] /
    (
        transform_df['recovery_score']
        + 1
    )
)

Weekend indicator

In [60]:
transform_df['is_weekend'] = (
    transform_df['day_of_week']
    .isin(
        [
            'Saturday',
            'Sunday'
        ]
    )
    .astype(int)
)

Age Group

In [61]:
transform_df['age_group'] = pd.cut(
    transform_df['age'],
    bins=[
        0,
        25,
        35,
        50,
        100
    ],
    labels=[
        '18-25',
        '26-35',
        '36-50',
        '50+'
    ]
)

####Validasi Kualitas Data

In [62]:
print(
    "Duplicate:",
    transform_df.duplicated(
        subset=['user_id','date']
    ).sum()
)

Duplicate: 0

In [63]:
transform_df.isnull().sum()

user_id                      0
date                         0
day_of_week                  0
age                          0
gender                       0
weight_kg                    0
height_cm                    0
fitness_level                0
primary_sport                0
recovery_score               0
day_strain                   0
sleep_hours                  0
sleep_efficiency             0
sleep_performance            0
light_sleep_hours            0
rem_sleep_hours              0
deep_sleep_hours             0
wake_ups                     0
time_to_fall_asleep_min      0
hrv                          0
resting_heart_rate           0
hrv_baseline                 0
rhr_baseline                 0
respiratory_rate             0
skin_temp_deviation          0
calories_burned              0
workout_completed            0
activity_type                0
activity_duration_min        0
activity_strain              0
avg_heart_rate               0
max_heart_rate               0
activity_calories            0
hr_zone_1_min                0
hr_zone_2_min                0
hr_zone_3_min                0
hr_zone_4_min                0
hr_zone_5_min                0
workout_time_of_day          0
recovery_score_norm          0
sleep_hours_norm             0
gender_encoded               0
temperature                  0
humidity                     0
bmi                          0
recovery_level               0
sleep_quality                0
strain_level               620
fatigue_index                0
is_weekend                   0
age_group                    0
dtype: int64

In [64]:
print(
    transform_df['recovery_score']
    .between(0,100)
    .all()
)

True

In [65]:
print(
    transform_df['date'].dtype
)

datetime64[ns]

In [66]:
print(
    transform_df['user_id']
    .notnull()
    .all()
)

True

Distribution Check

In [51]:
transform_df['recovery_score'].describe()

count    100000.000000
mean         65.130442
std          17.698584
min           5.000000
25%          52.400000
50%          64.500000
75%          77.400000
max         100.000000
Name: recovery_score, dtype: float64

In [50]:
transform_df['sleep_hours'].describe()

count    100000.000000
mean          7.296272
std           0.972416
min           4.000000
25%           6.650000
50%           7.460000
75%           8.030000
max          10.000000
Name: sleep_hours, dtype: float64

In [49]:
transform_df.to_csv(
    "whoop_fitness_transformed.csv",
    index=False
)

print(
    "Transform Finished Successfully"
)

Transform Finished Successfully

####6.3 Load

Membuat koneksi db

In [38]:
import sqlite3

conn = sqlite3.connect("whoop_fitness_dataset.db")

cursor = conn.cursor()

print("Database Connected")

Database Connected

In [42]:
dim_user = transform_df[
    [
        'user_id',
        'age',
        'gender',
        'fitness_level',
        'primary_sport'
    ]
].drop_duplicates()

In [67]:
dim_user.head()

         user_id  age  gender fitness_level    primary_sport
0     USER_00001   56  Female      Beginner  Weight Training
323   USER_00002   56    Male         Elite         CrossFit
632   USER_00003   43    Male  Intermediate          Cycling
957   USER_00004   36    Male      Advanced         CrossFit
1274  USER_00005   47  Female  Intermediate          Cycling

In [68]:
dim_user.to_sql(
    "dim_user",
    conn,
    if_exists="replace",
    index=False
)

286

In [69]:
dim_date = transform_df[
    [
        'date',
        'day_of_week',
        'is_weekend'
    ]
].drop_duplicates()

In [70]:
dim_date.to_sql(
    "dim_date",
    conn,
    if_exists="replace",
    index=False
)

399

In [71]:
dim_activity = transform_df[
    [
        'activity_type',
        'activity_duration_min',
        'activity_strain',
        'workout_time_of_day'
    ]
].drop_duplicates()

In [72]:
dim_activity.to_sql(
    "dim_activity",
    conn,
    if_exists="replace",
    index=False
)

51303

In [73]:
fact_fitness = transform_df[
    [
        'user_id',
        'date',
        'activity_type',
        'recovery_score',
        'sleep_hours',
        'sleep_efficiency',
        'day_strain',
        'hrv',
        'calories_burned',
        'temperature',
        'humidity',
        'fatigue_index'
    ]
]

In [74]:
fact_fitness.to_sql(
    "fact_fitness",
    conn,
    if_exists="replace",
    index=False
)

100000

In [75]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

           name
0      dim_user
1      dim_date
2  dim_activity
3  fact_fitness

In [76]:
pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM fact_fitness",
    conn
)

   total_rows
0      100000

In [77]:
pd.read_sql(
    """
    SELECT COUNT(DISTINCT user_id)
    AS total_users
    FROM dim_user
    """,
    conn
)

   total_users
0          286

Query 1

In [78]:
query1 = """
SELECT
    AVG(recovery_score) AS avg_recovery
FROM fact_fitness
"""

print("QUERY 1 - Average Recovery Score")
display(pd.read_sql(query1, conn))

QUERY 1 - Average Recovery Score

   avg_recovery
0     65.130442

Query 2 - Average Sleep Hours by Gender

In [79]:
query2 = """
SELECT
    u.gender,
    AVG(f.sleep_hours) AS avg_sleep_hours
FROM fact_fitness f
JOIN dim_user u
    ON f.user_id = u.user_id
GROUP BY u.gender
"""

print("QUERY 2 - Average Sleep Hours by Gender")
display(pd.read_sql(query2, conn))

QUERY 2 - Average Sleep Hours by Gender

   gender  avg_sleep_hours
0  Female         7.327787
1    Male         7.271243

Query 3 - Recovery Score by Fitness Level

In [80]:
query3 = """
SELECT
    u.fitness_level,
    AVG(f.recovery_score) AS avg_recovery
FROM fact_fitness f
JOIN dim_user u
    ON f.user_id = u.user_id
GROUP BY u.fitness_level
ORDER BY avg_recovery DESC
"""

print("QUERY 3 - Recovery by Fitness Level")
display(pd.read_sql(query3, conn))

QUERY 3 - Recovery by Fitness Level

  fitness_level  avg_recovery
0         Elite     65.895597
1      Advanced     65.835293
2  Intermediate     65.673598
3      Beginner     62.442958

Query 4 - Average Calories Burned by Activity Type

In [81]:
query4 = """
SELECT
    activity_type,
    AVG(calories_burned) AS avg_calories
FROM fact_fitness
GROUP BY activity_type
ORDER BY avg_calories DESC
"""

print("QUERY 4 - Calories Burned by Activity")
display(pd.read_sql(query4, conn))

QUERY 4 - Calories Burned by Activity

     activity_type  avg_calories
0  Weight Training   3350.618458
1             HIIT   3342.864764
2         Swimming   3332.933870
3          Walking   3329.245576
4          Cycling   3326.171433
5          Running   3325.824738
6         CrossFit   3322.446815
7             Yoga   3321.815580
8         Rest Day   3233.801413

Query 5 - Weekend vs Weekday Recovery

In [82]:
query5 = """
SELECT
    d.is_weekend,
    AVG(f.recovery_score) AS avg_recovery
FROM fact_fitness f
JOIN dim_date d
    ON f.date = d.date
GROUP BY d.is_weekend
"""

print("QUERY 5 - Weekend vs Weekday Recovery")
display(pd.read_sql(query5, conn))

QUERY 5 - Weekend vs Weekday Recovery

   is_weekend  avg_recovery
0           0     65.116039
1           1     65.166422

Query 6 - Average HRV by Primary Sport

In [83]:
query6 = """
SELECT
    u.primary_sport,
    AVG(f.hrv) AS avg_hrv
FROM fact_fitness f
JOIN dim_user u
    ON f.user_id = u.user_id
GROUP BY u.primary_sport
ORDER BY avg_hrv DESC
"""

print("QUERY 6 - Average HRV by Sport")
display(pd.read_sql(query6, conn))

QUERY 6 - Average HRV by Sport

     primary_sport    avg_hrv
0          Cycling  78.181411
1         Swimming  75.969316
2  Weight Training  75.538940
3         CrossFit  74.787897
4          Walking  73.299820
5          Running  72.041559
6             HIIT  69.162202
7             Yoga  68.126808

Query 7 - Highest Average Day Strain by Activity

In [84]:
query7 = """
SELECT
    activity_type,
    AVG(day_strain) AS avg_day_strain
FROM fact_fitness
GROUP BY activity_type
ORDER BY avg_day_strain DESC
"""

print("QUERY 7 - Highest Strain Activities")
display(pd.read_sql(query7, conn))

QUERY 7 - Highest Strain Activities

     activity_type  avg_day_strain
0  Weight Training       10.341631
1             HIIT       10.286031
2         Swimming       10.233150
3          Walking       10.212149
4          Running       10.179646
5         CrossFit       10.170139
6          Cycling       10.166173
7             Yoga       10.159712
8         Rest Day        9.550741

Query 8 - Daily Sleep Trend

In [85]:
query8 = """
SELECT
    date,
    AVG(sleep_hours) AS avg_sleep
FROM fact_fitness
GROUP BY date
ORDER BY date
"""

print("QUERY 8 - Sleep Trend by Date")
display(pd.read_sql(query8, conn))

QUERY 8 - Sleep Trend by Date

                    date  avg_sleep
0    2023-01-01 00:00:00   7.310035
1    2023-01-02 00:00:00   7.342063
2    2023-01-03 00:00:00   7.340490
3    2023-01-04 00:00:00   7.352378
4    2023-01-05 00:00:00   7.238392
..                   ...        ...
394  2024-01-30 00:00:00   7.437647
395  2024-01-31 00:00:00   7.351875
396  2024-02-01 00:00:00   6.969091
397  2024-02-02 00:00:00   7.210000
398  2024-02-03 00:00:00   6.665000

[399 rows x 2 columns]

In [86]:
conn.commit()

conn.close()

print("LOAD SUCCESS")

LOAD SUCCESS

####7. ELT

7.1 Extract and load

In [89]:
import sqlite3
import pandas as pd

conn_elt = sqlite3.connect("whoop_elt_warehouse.db")

df.to_sql(
    "raw_whoop_data",
    conn_elt,
    if_exists="replace",
    index=False
)

100000

In [90]:
weather_df = pd.DataFrame({
    "temperature":[weather_json['main']['temp']],
    "humidity":[weather_json['main']['humidity']]
})

weather_df.to_sql(
    "raw_weather_data",
    conn_elt,
    if_exists="replace",
    index=False
)

1

Metadataa

In [92]:
metadata = pd.DataFrame({
    "table_name":["raw_whoop_data"],
    "rows":[df.shape[0]],
    "columns":[df.shape[1]]
})

metadata.to_sql(
    "load_metadata",
    conn_elt,
    if_exists="replace",
    index=False
)

1

Transform

In [93]:
elt_df = pd.read_sql(
    "SELECT * FROM raw_whoop_data",
    conn_elt
)

In [94]:
elt_df['workout_time_of_day'] = (
    elt_df['workout_time_of_day']
    .fillna('No Workout')
)

In [95]:
elt_df['date'] = pd.to_datetime(
    elt_df['date']
)

Join di warehouse

In [96]:
weather_raw = pd.read_sql(
    "SELECT * FROM raw_weather_data",
    conn_elt
)

elt_df['temperature'] = weather_raw.loc[0,'temperature']
elt_df['humidity'] = weather_raw.loc[0,'humidity']

Agregasi analitik

In [97]:
agg_recovery = (
    elt_df
    .groupby('fitness_level')
    .agg({
        'recovery_score':'mean',
        'sleep_hours':'mean',
        'hrv':'mean'
    })
    .reset_index()
)

In [98]:
agg_recovery.to_sql(
    "agg_recovery_by_fitness",
    conn_elt,
    if_exists="replace",
    index=False
)

4

In [99]:
agg_activity = (
    elt_df
    .groupby('activity_type')
    .agg({
        'recovery_score':'mean',
        'day_strain':'mean',
        'calories_burned':'mean'
    })
    .reset_index()
)

In [100]:
agg_activity.to_sql(
    "agg_activity_metrics",
    conn_elt,
    if_exists="replace",
    index=False
)

9

Feature Engineering Berbasis Warehouse

In [101]:
elt_df['recovery_gap'] = (
    elt_df['recovery_score']
    - elt_df['sleep_performance']
)

In [102]:
elt_df['hrv_delta'] = (
    elt_df['hrv']
    - elt_df['hrv_baseline']
)

In [103]:
elt_df['rhr_delta'] = (
    elt_df['resting_heart_rate']
    - elt_df['rhr_baseline']
)

In [104]:
elt_df['training_load_ratio'] = (
    elt_df['activity_strain']
    /
    (elt_df['day_strain'] + 1)
)

In [105]:
elt_df['sleep_debt'] = (
    8 - elt_df['sleep_hours']
)

In [106]:
elt_df.to_sql(
    "elt_final_dataset",
    conn_elt,
    if_exists="replace",
    index=False
)

100000

In [108]:
import os

os.listdir()

['.config',
 'whoop_fitness_dataset.db',
 'whoop_data_warehouse.db',
 'whoop_fitness_transformed.csv',
 'whoop_elt_warehouse.db',
 'drive',
 'sample_data']